# Project: dev_studentCourseSelectionSystem_v1.0
# Makefile created by Dev-C++ 5.4.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o service_manager.o operation_student.o service_student.o file_access.o menus.o operation_manager.o $(RES)
LINKOBJ  = main.o service_manager.o operation_student.o service_student.o file_access.o menus.o operation_manager.o $(RES)
LIBS     = -L"G:/算法竞赛/蓝桥杯/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"G:/算法竞赛/蓝桥杯/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"G:/算法竞赛/蓝桥杯/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/include"
BIN      = dev_studentCourseSelectionSystem_v1.0.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

service_manager.o: service_manager.c
	$(CC) -c service_manager.c -o service_manager.o $(CFLAGS)

operation_student.o: operation_student.c
	$(CC) -c operation_student.c -o operation_student.o $(CFLAGS)

service_student.o: service_student.c
	$(CC) -c service_student.c -o service_student.o $(CFLAGS)

file_access.o: file_access.c
	$(CC) -c file_access.c -o file_access.o $(CFLAGS)

menus.o: menus.c
	$(CC) -c menus.c -o menus.o $(CFLAGS)

operation_manager.o: operation_manager.c
	$(CC) -c operation_manager.c -o operation_manager.o $(CFLAGS)
