# Project: dev_studentCourseSelectionSystem_v1.0
# Makefile created by Dev-C++ 5.4.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o manager_function.o student_function.o $(RES)
LINKOBJ  = main.o manager_function.o student_function.o $(RES)
LIBS     = -L"G:/算法竞赛/蓝桥杯/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"G:/算法竞赛/蓝桥杯/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"G:/算法竞赛/蓝桥杯/Dev-cpp5.4.0及API帮助文档/Dev-Cpp/MinGW32/include"
BIN      = dev_studentCourseSelectionSystem_v1.0.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

manager_function.o: manager_function.c
	$(CC) -c manager_function.c -o manager_function.o $(CFLAGS)

student_function.o: student_function.c
	$(CC) -c student_function.c -o student_function.o $(CFLAGS)
